name: hoauth2
version: '1.10.1'
synopsis: Haskell OAuth2 authentication client
description: ! 'Haskell OAuth2 authentication client. Tested with the following services:


  * AzureAD: <https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code>


  * Google: <https://developers.google.com/accounts/docs/OAuth2WebServer>


  * Github: <http://developer.github.com/v3/oauth/>


  * Facebook: <http://developers.facebook.com/docs/facebook-login/>


  * Fitbit: <http://dev.fitbit.com/docs/oauth2/>


  * StackExchange: <https://api.stackexchange.com/docs/authentication>


  * DropBox: <https://www.dropbox.com/developers/reference/oauth-guide>


  * Weibo: <http://open.weibo.com/wiki/Oauth2>


  * Douban: <http://developers.douban.com/wiki/?title=oauth2>'
category: Network
author: Haisheng Wu
maintainer: Haisheng Wu <freizl@gmail.com>
copyright: Haisheng Wu
license: BSD-3
homepage: https://github.com/freizl/hoauth2
git: git://github.com/freizl/hoauth2.git
extra-source-files:
- README.md
ghc-options:
- -Wall
- -fwarn-tabs
- -funbox-strict-fields
- -fno-warn-unused-do-bind
dependencies:
- binary >=0.8.3.0 && <0.8.8
- text >=0.11 && <1.3
- bytestring >=0.9 && <0.11
- http-conduit >=2.1 && <2.4
- http-types >=0.11 && <0.13
- aeson >=1.3.0.0 && <1.5
- unordered-containers >=0.2.5
- uri-bytestring >=0.2.3.1 && <0.4
- microlens >=0.4.0 && <0.5
library:
  source-dirs: src
  exposed-modules:
  - Network.OAuth.OAuth2.HttpClient
  - Network.OAuth.OAuth2.Internal
  - Network.OAuth.OAuth2
  - Network.OAuth.OAuth2.TokenRequest
  - Network.OAuth.OAuth2.AuthorizationRequest
  dependencies:
  - base >=4 && <5
  - uri-bytestring-aeson >=0.1 && <0.2
  - exceptions >=0.8.3 && <0.11
flags:
  test:
    description: Build the executables
    manual: false
    default: false
stability: Beta
tested-with: ghc <=8.6.5
